# main function
def main():
    #Title and Introduction
    print("Marist Virtual Tour")
    print("Hello everyone! Welcome to Marist College.")
    print("I'll be your tour guide as I show you some of our locations here")
    print("on campus. Enjoy the tour.")
    input("Press the enter key to begin the tour: ")
    #Location 1 - Student Center
    print()
    print("Murray Student Center")
    print("Our first location here is the Murray Student Center. This location")
    print("serves as the center point of the college. It brings together all")
    print("the members of Marist College. It provides various student services")
    print("and serves as a place where students can meet and organize events.")
    print("Some of these services include dining services, student lounge,")
    print("the campus post office, and the campus bookstore.")
    input("Press the enter key to go to the next location: ")
    #Location 2 - Donnelly Hall
    print()
    print("Donnelly Hall")
    print("Our next location here is Donnelly Hall. This location mainly houses")
    print("our technology services and other offices that are available to")
    print("our students here on campus. Some of these services include")
    print("Financial services, the Help Desk, Advising and Academic Services")
    print("and the Computer Lab.")
    input("Press the enter key to go to the next location: ")
    #Location 3 - Hancock Center
    print()
    print("Hancock Center")
    print("Our next location here is the Hancock Center. This location is")
    print("for our School of Computer Science and Mathematics. However, it also")
    print("houses our Study Abroad offices, which manages our programs for students")
    print("who want to go and study in another country, such as our campus in")
    print("Florence, Italy. It also houses our Investment Center and Trading Room")
    print("and our Center for Teaching Excellence.")
    input("Press the enter key to go to the next location: ")
    #Location 4 - McCann Center
    print()
    print("McCann Center")
    print("Our next location here is the McCann Center. This location is mostly")
    print("known to be our sports center here on campus. It houses our Athletic")
    print("Department, our fitness center, our Center for Sports Medicine, and")
    print("other sports services. It also houses our Admissions Visitor Center")
    print("for people who come to visit our campus.")
    input("Press the enter key to go to the next location: ")
    #Location #5 - Cannavino Library
    print()
    print("Cannavino Library")
    print("Our next location here is the Cannavino Library. This location serves")
    print("as our main library here on campus. It also serves as a place where")
    print("students can catch up on their work and study without any distractions.")
    print("It also houses our Center for Career Services, Center for Multicultural")
    print("Affairs, and our Digital Education services.")
    input("Press the enter key to go to the next location: ")
    #Location #6 - The Chapel
    print()
    print("The Chapel")
    print("Our next location here is the Chapel. The Chapel serves as an")
    print("Inter-Faith Prayer room, where anyone can come in for quiet")
    print("prayer from 7 am to 10 pm. It also provides Mass services")
    print("Monday through Thursday at 12:15 pm and on Sundays at both")
    print("12 pm and 6:30 pm.")
    input("Press the enter key to go to the next location: ")
    #Location #7 - McCormick Hall
    print()
    print("McCormick Hall")
    print("Our next location here is McCormick Hall. This location serves as a")
    print("residence hall for our upperclassmen. Unlike the freshman residence")
    print("halls we have here on campus, residents of this hall are responsible")
    print("for their own cooking and cleaning of their apartment. This location")
    print("also serves as one of our dining locations here on campus, also")
    print("known as North End Dining.")
    input("Press the enter key to go to the next location: ")
    #Location 8 - Steel Plant Studios and Gallery
    print()
    print("Steel Plant Studios and Gallery")
    


main()
